dist: xenial
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
  - sudo apt-get install -y lttoolbox-dev libxml2-utils xsltproc libpcre3 swig
script:
  - ./autogen.sh  --enable-python-bindings
  - ./configure
  - make
  - make test
